@csrf
<div class="grid gap-5 sm:grid-cols-2">
    <div><label for="name" class="text-sm font-medium text-navy">Name</label><input id="name" name="name" value="{{ old('name', $member->name ?? '') }}" required class="mt-1.5 w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent">@error('name')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="photo" class="text-sm font-medium text-navy">Profile photo</label><input id="photo" name="photo" type="file" accept="image/jpeg,image/png,image/webp" @required(!isset($member)) class="mt-1.5 block w-full rounded-lg border border-navy/15 bg-white px-3 py-2 text-sm file:mr-4 file:rounded-md file:border-0 file:bg-surface file:px-3 file:py-2 file:text-sm file:font-semibold file:text-navy"><p class="mt-1.5 text-xs text-muted">JPG, PNG, or WebP, maximum 5 MB.</p>@error('photo')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror @if (isset($member) && $member->photo_path)<img src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($member->photo_path) }}" alt="{{ $member->name }}" class="mt-3 h-20 w-20 rounded-full object-cover">@endif</div>
    <div><label for="role" class="text-sm font-medium text-navy">Role</label><input id="role" name="role" value="{{ old('role', $member->role ?? '') }}" required class="mt-1.5 w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent">@error('role')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="expertise" class="text-sm font-medium text-navy">Expertise</label><input id="expertise" name="expertise" value="{{ old('expertise', $member->expertise ?? '') }}" class="mt-1.5 w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent">@error('expertise')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="sort_order" class="text-sm font-medium text-navy">Display order</label><input id="sort_order" name="sort_order" type="number" min="0" max="999" value="{{ old('sort_order', $member->sort_order ?? 0) }}" required class="mt-1.5 w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent">@error('sort_order')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label for="bio" class="text-sm font-medium text-navy">Description</label><textarea id="bio" name="bio" rows="5" class="mt-1.5 w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent">{{ old('bio', $member->bio ?? '') }}</textarea>@error('bio')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
    <label class="flex items-center gap-2 text-sm font-medium text-navy"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $member->is_active ?? true)) class="rounded border-navy/25 text-accent focus:ring-accent/40"> Visible on public website</label>
</div>
<div class="mt-6 flex flex-wrap gap-3"><button type="submit" class="admin-btn-primary">{{ $submitLabel }}</button><a href="{{ route('admin.team.index') }}" class="admin-btn-secondary">Cancel</a></div>
