<x-admin.layout title="Consultation Request">
    <div class="mx-auto max-w-4xl space-y-6">
        <div class="flex flex-wrap items-end justify-between gap-4"><div><a href="{{ route('admin.consultation-requests.index') }}" class="text-sm font-medium text-muted hover:text-accent">&larr; Back to Requests</a><h1 class="mt-3 text-2xl font-bold text-navy">{{ $requestItem->name }}</h1><p class="mt-1 text-sm text-muted">{{ $requestItem->company ?: 'Individual client' }} &middot; {{ $requestItem->created_at->format('d M Y H:i') }}</p></div><form method="POST" action="{{ route('admin.consultation-requests.destroy', $requestItem) }}" onsubmit="return confirm('Delete this request?')">@csrf @method('DELETE')<button type="submit" class="admin-btn-secondary text-red-600 hover:border-red-300 hover:text-red-700">Delete</button></form></div>
        @if (session('status'))<div class="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ session('status') }}</div>@endif
        <div class="grid gap-6 lg:grid-cols-3"><div class="admin-card p-5 lg:col-span-2"><h2 class="text-base font-semibold text-navy">Consultation Chat</h2><div class="mt-5 space-y-3">@forelse ($requestItem->chatMessages as $chatMessage)<div class="rounded-lg p-4 {{ $chatMessage->sender_type === 'admin' ? 'ml-8 bg-navy text-white' : 'mr-8 bg-surface text-charcoal' }}"><div class="flex items-center justify-between gap-3 text-xs opacity-70"><span>{{ $chatMessage->sender_type === 'admin' ? 'Admin' : $requestItem->name }}</span><span>{{ $chatMessage->created_at->format('d M Y H:i') }}</span></div><p class="mt-2 whitespace-pre-line text-sm leading-relaxed">{{ $chatMessage->body }}</p></div>@empty<p class="text-sm text-muted">No chat messages yet.</p>@endforelse</div><form method="POST" action="{{ route('admin.consultation-requests.messages.store', $requestItem) }}" class="mt-6 border-t border-navy/10 pt-5">@csrf<label for="reply_body" class="text-sm font-medium text-navy">Reply to visitor</label><textarea id="reply_body" name="body" rows="4" required class="mt-1.5 w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"></textarea><button type="submit" class="admin-btn-primary mt-3">Send Reply</button></form></div>
            <div class="admin-card p-5"><h2 class="text-base font-semibold text-navy">Update Status</h2><form method="POST" action="{{ route('admin.consultation-requests.update', $requestItem) }}" class="mt-5 space-y-4">@csrf @method('PUT')<div><label for="status" class="text-sm font-medium text-navy">Status</label><select id="status" name="status" class="mt-1.5 w-full rounded-lg border border-navy/15 bg-white px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent">@foreach (['new' => 'New', 'in_review' => 'In Review', 'contacted' => 'Contacted', 'converted' => 'Converted', 'closed' => 'Closed'] as $value => $label)<option value="{{ $value }}" @selected($requestItem->status === $value)>{{ $label }}</option>@endforeach</select></div><div><label for="admin_notes" class="text-sm font-medium text-navy">Admin notes</label><textarea id="admin_notes" name="admin_notes" rows="5" class="mt-1.5 w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent">{{ $requestItem->admin_notes }}</textarea></div><button type="submit" class="admin-btn-primary w-full">Save Status</button></form></div>
        </div>
    </div>
</x-admin.layout>
