@csrf
<div class="grid gap-5 sm:grid-cols-2">
    <div><label for="title" class="text-sm font-medium text-navy">Title</label><input id="title" name="title" value="{{ old('title', $insight->title ?? '') }}" required class="mt-1.5 w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent">@error('title')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="slug" class="text-sm font-medium text-navy">Slug</label><input id="slug" name="slug" value="{{ old('slug', $insight->slug ?? '') }}" required class="mt-1.5 w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent">@error('slug')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="category" class="text-sm font-medium text-navy">Category</label><input id="category" name="category" value="{{ old('category', $insight->category ?? '') }}" required class="mt-1.5 w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent">@error('category')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="author" class="text-sm font-medium text-navy">Author</label><input id="author" name="author" value="{{ old('author', $insight->author ?? 'NEXORA Editorial Team') }}" required class="mt-1.5 w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent">@error('author')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="published_at" class="text-sm font-medium text-navy">Publication date</label><input id="published_at" name="published_at" type="date" value="{{ old('published_at', isset($insight) && $insight->published_at ? $insight->published_at->format('Y-m-d') : now()->format('Y-m-d')) }}" class="mt-1.5 w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent">@error('published_at')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
    <label class="flex items-center gap-2 self-end pb-2 text-sm font-medium text-navy"><input type="checkbox" name="is_published" value="1" @checked(old('is_published', $insight->is_published ?? true)) class="rounded border-navy/25 text-accent focus:ring-accent/40"> Published on public website</label>
    <div class="sm:col-span-2"><label for="cover_image" class="text-sm font-medium text-navy">Cover image</label><select id="cover_image" name="cover_image" class="mt-1.5 w-full rounded-lg border border-navy/15 bg-white px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"><option value="">No cover image</option>@foreach ($mediaFiles as $mediaFile)<option value="{{ $mediaFile['path'] }}" @selected(old('cover_image', $insight->cover_image ?? '') === $mediaFile['path'])>{{ $mediaFile['name'] }}</option>@endforeach</select><p class="mt-1.5 text-xs text-muted">Upload images in Media Library first, then select one here.</p>@error('cover_image')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label for="excerpt" class="text-sm font-medium text-navy">Excerpt</label><textarea id="excerpt" name="excerpt" rows="3" required class="mt-1.5 w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent">{{ old('excerpt', $insight->excerpt ?? '') }}</textarea>@error('excerpt')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label for="body" class="text-sm font-medium text-navy">Article body</label><textarea id="body" name="body" rows="14" class="mt-1.5 w-full rounded-lg border border-navy/15 px-3.5 py-2.5 text-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent">{{ old('body', $insight->body ?? '') }}</textarea>@error('body')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
</div>
<div class="mt-6 flex flex-wrap gap-3"><button type="submit" class="admin-btn-primary">{{ $submitLabel }}</button><a href="{{ route('admin.insights.index') }}" class="admin-btn-secondary">Cancel</a></div>
